baseURL: 'https://ligapedd.vercel.app/'
languageCode: 'pt-br'
title: 'Liga Pernambucana de Direito Digital'
theme: 'ligapedd-v2'

Taxonomies: {
    category: "categorias",
    author: "colaboradores",
    grupo: "grupos"
}

Permalinks: {
    pages: "/:filename/"
}